import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next AppXX',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={inter.className}>
        <div className='flex fixed justify-around w-full bg-slate-100'>
          <Link href='/csr'>CSR</Link>
          <Link href='/ssg'>SSG</Link>
          <Link href='/ssr'>SSR</Link>
          <Link href='/isr'>ISR</Link>
          <Link href='/photos'>Photos</Link>
        </div>
        <div className='container mx-auto flex flex-col items-center justify-center pl-5 py-5'>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
