import { Metadata } from 'next';
import { Todo as TodoType, getTodo } from '@/lib/placeholder';

type Params = {
  params: { todoId: string };
};

// export const metadata: Metadata = {
//   title: 'Todo',
//   description: 'Generated by create next app',
// };

export async function generateMetadata({
  params: { todoId },
}: Params): Promise<Metadata> {
  const todo: TodoType = await getTodo(+todoId);
  return {
    title: todo.title,
  };
}

export default async function Todo({ params: { todoId } }: Params) {
  const todo = await getTodo(+todoId);
  return (
    <>
      <h1 className='text-2xl'>ID: {todoId}</h1>
      <h3 className='text-xl'>{todo.title}</h3>
    </>
  );
}
